# 3.Statistical analysis

In [26]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from IPython.display import Image, display
%matplotlib inline

In [27]:
train = pd.read_csv('../data/Preprocessed/train.csv')
test = pd.read_csv('../data/Preprocessed/test.csv')

In [28]:
train.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked', 'Cabin_First',
       'FamilyCount', 'title'],
      dtype='object')

In [46]:
# we will select just the columns that we want to use in our analysis
trainML = train[['Survived', 'Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Ticket','Fare', 'Embarked', 'FamilyCount','Cabin_First', 'title']]
trainML = trainML.dropna()

In [47]:
trainML.isnull().sum()


Survived       0
Pclass         0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked       0
FamilyCount    0
Cabin_First    0
title          0
dtype: int64

## 3.1 Starting regressions


In [51]:
from sklearn.linear_model import LogisticRegression
log_reg = LogisticRegression()

### 3.1.1 Logistic Regression: Survival on age

In [52]:
X_Age = trainML[['Age']].values
y = trainML['Survived'].values
# Use the fit method to train
log_reg.fit(X_Age,y)
# Make a prediction
y_predict = log_reg.predict(X_Age)
(y == y_predict).mean()

0.681592039800995

### 3.1.2 Logistic regression: Survival on sex / Pclass

In [53]:
X_sex = pd.get_dummies(trainML['Sex']).values
y = trainML['Survived'].values
# Use the fit method to train
log_reg.fit(X_sex, y)
# Make a prediction
y_predict = log_reg.predict(X_sex)
(y == y_predict).mean()

0.746268656716418

### 3.1.3 random Random forest (on numerical variables)

In [ ]:
from sklearn.ensemble import RandomForestClassifier
X = trainML[['Age', 'SibSp', 'Parch',
       'Fare', 'FamilyCount']].values # Taking all the numerical values
y = trainML['Survived'].values
RF = RandomForestClassifier()
RF.fit(X, y)
# Make a prediction
y_predict = RF.predict(X)
(y == y_predict).mean()


## 3.2 Logistic regression
It is useful in the prediction on a binary output variable. To perform it we will use the logistic function, which is the canonical link function in the GLM framework, and this one will be maximized using the log-likelyhood. In a nutshell this means that we will not define the response Y directly, but we will model the porbability that Y belongs to a particular category fiven the input.
From a computationperspective, we will have to remember that to define the maximum of the likelyhood will be necessary to compute the derivative of the log-likelyhood. The derivative will not be anymore linear in \beta and this means that the porblem doesn't have a closed form solution. We will have a iterative algorithm:
- Newton Rapson: at every step we will have to compute the inverse of (X^T W(t) X) where W(t) changes at every step, then it is computationally expensive
- Majorize Minimize: minimize the loss funcition by approximating it with a simpler one


In [34]:
from sklearn.metrics import accuracy_score, confusion_matrix

In [42]:
train_ML = train[['Age', 'SibSp', 'Parch','Fare', 'FamilyCount','Survived']]
X = train_ML.drop('Survived', axis = 1)
y = train_ML['Survived']

In [45]:
log_reg.fit(X, y)
y_pred = log_reg.predict(X)
y_pred
(y == y_pred).mean()

0.6936026936026936

### 3.2.1.Accuracy scores and confusion matrix on basic Multiple logistic regression
To actually evaluate the performance of our model would be necessary to know what are the actual results, ten, as in our case, we will rely on a train, test split to evaluate if it is actually good at predicting the result. The following will be useful as metrics to compare different ML models' performance

In [55]:
X = train_ML.drop('Survived', axis = 1)
y = train_ML['Survived']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.33, random_state = 0)

In [56]:
log_reg.fit(X_train, y_train)
y_pred = log_reg.predict(X_test)
y_pred

array([0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0])

In [57]:
accuracy_score(y_pred, y_test)

0.711864406779661

In [58]:
confusion_matrix(y_pred, y_test)

array([[178,  79],
       [  6,  32]])

### 3.2.2. Adding categorical variables


In [77]:
train_cat = pd.get_dummies(train, columns=['Sex', 'Pclass','Embarked'], drop_first=True).drop(['title','Cabin','Ticket','Name','Cabin_First'],axis = 1)

In [76]:
train_cat.head()

PassengerId  Survived  Age  SibSp  Parch     Fare Cabin_First  FamilyCount  \
0            1         0   22      1      0   7.2500         NaN            1   
1            2         1   38      1      0  71.2833           C            1   
2            3         1   26      0      0   7.9250         NaN            0   
3            4         1   35      1      0  53.1000           C            1   
4            5         0   35      0      0   8.0500         NaN            0   

   Sex_male  Pclass_2  Pclass_3  Embarked_Q  Embarked_S  
0         1         0         1           0           1  
1         0         0         0           0           0  
2         0         0         1           0           1  
3         0         0         0           0           1  
4         1         0         1           0           1

In [78]:
X = train_cat.drop('Survived', axis = 1)
y = train_cat['Survived']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.33, random_state = 0)
log_reg.fit(X_train, y_train)
y_pred = log_reg.predict(X_test)
y_pred

/Users/valedipalo/venvs/demoenv39/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


array([0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1,
       1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0,
       1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1,
       0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1,
       0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1])

In [79]:
accuracy_score(y_pred, y_test)


0.7898305084745763

In [80]:
confusion_matrix(y_pred, y_test)

array([[157,  35],
       [ 27,  76]])

### 3.2.3 Conclusion
In this section we evaluated the basis of the model, now we want to obtain some basic results for test actual test dataset

In [84]:
X_real_test = pd.read_csv('../data/Preprocessed/test.csv')

In [85]:
train_ML = train[['Age', 'SibSp', 'Parch','Fare', 'FamilyCount','Survived']]
X = train_ML.drop('Survived', axis = 1)
y = train_ML['Survived']
log_reg.fit(X, y)
y_pred = log_reg.predict(X_real_test)


/Users/valedipalo/venvs/demoenv39/lib/python3.9/site-packages/sklearn/base.py:493: FutureWarning: The feature names should match those that were passed during fit. Starting version 1.2, an error will be raised.
Feature names unseen at fit time:
- Cabin
- Cabin_First
- Embarked
- Name
- PassengerId
- ...

  warnings.warn(message, FutureWarning)


ValueError: could not convert string to float: 'Kelly, Mr. James'

In [ ]:
#results with categorical variables
X_cat = train_cat.drop('Survived', axis = 1)
y_cat = train_cat['Survived']
log_reg.fit(X_cat, y_cat)
y_cat_pred = log_reg.predict(X_real_test)
